name: methanohunt
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - snakemake>=9.0
  - hmmer
  - pplacer
  - minimap2
  - samtools
  - pandas
  - natsort
  - plotly
  - click
  - pysam
  - pip
